POST Validation tests for User.
hmcts/snl-api-fh-test pull request #10
Opened 2021-02-05 17:36 UTC by JAidhy

V1.4e/createUserMessage.json

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-06 08:35 UTC, pats-john requested changes

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +            "Valid personAuthorisedSessionTypes, ADHOC",
May be move this to a CSV File...

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +import java.util.*;
OPtimise your imports in Intellij using ctrl options O.

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +        if (personPhoneKey.equalsIgnoreCase("Valid phone number 19Chars")) {
Ideally use a Switch Case Here...

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +        if (personContactEmailKey.equalsIgnoreCase("Valid email 100 Chars")) {
Same Comment above...

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Bug Here ....The Verifier for a Negative Test should be a Negative Verifier....

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Negative Verifier....

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Negative verifier....

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Negative Verifier...

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                    getSnlSuccessVerifier(),
Negative Verifier....

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Negative Verifier...

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/ResourcesPayloadValidationTest.java
> +    final void generatePayloadWithRandomHMCTSIDAndField(final Object formatValue, final String templatePath) throws IOException {
I am confident that we already have a method like this. Do we have to Duplicate?????

2021-02-06 08:35 UTC, pats-john commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/ResourcesPayloadValidationTest.java
> +    final void generatePayloadWithRandomHMCTSIDAndPersonField(final Object formatValue,
What is the purpose of this util method...?Just need to discuss....

2021-02-08 16:37 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +            "Valid personAuthorisedSessionTypes, ADHOC",
Implemented using csv file.

2021-02-08 16:37 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +        if (personPhoneKey.equalsIgnoreCase("Valid phone number 19Chars")) {
Implemented as suggested

2021-02-08 16:38 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +        if (personContactEmailKey.equalsIgnoreCase("Valid email 100 Chars")) {
Implemented as suggested

2021-02-08 16:38 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Implemented as suggested

2021-02-08 16:38 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Implemented as suggested

2021-02-08 16:38 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                    getSnlSuccessVerifier(),
Implemented as suggested

2021-02-08 16:38 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/POSTResourcesByUserPayloadValidationTest.java
> +                getSnlSuccessVerifier(),
Implemented as suggested

2021-02-08 16:39 UTC, JAidhy commented on src/acceptanceTest/java/uk/gov/hmcts/futurehearings/snl/acceptance/resources/ResourcesPayloadValidationTest.java
> +    final void generatePayloadWithRandomHMCTSIDAndField(final Object formatValue, final String templatePath) throws IOException {
Not using this method anymore, I have commented it.

2021-02-08 18:00 UTC, pats-john approved these changes

2021-02-08 18:00 UTC, merged